services:
  database:
    container_name: postgres-database
    image: postgres:18-alpine
    restart: unless-stopped

    environment:
      POSTGRES_INITDB_ARGS: '--encoding=UTF8 --locale=C'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'secret'
      POSTGRES_DB: 'api'

    ports:
      - '5432:5432'

    volumes:
      - pgdata:/var/lib/postgresql
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
    driver: local
